/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import Controllers.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.runtime.regexp.joni.exception.ErrorMessages;
import model.user;
import static sun.security.krb5.KrbException.errorMessage;

/**
 *
 * @author GABRIEL
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("close.png")).getImage());
        RED1.setVisible(false);
        RED2.setVisible(false);
        RED3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RED1 = new javax.swing.JLabel();
        RED2 = new javax.swing.JLabel();
        RED3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        confirmpass = new javax.swing.JPasswordField();
        password = new javax.swing.JPasswordField();
        HoverBar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(980, 630));
        setPreferredSize(new java.awt.Dimension(980, 630));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RED1.setFont(new java.awt.Font("PacFont", 1, 14)); // NOI18N
        RED1.setForeground(new java.awt.Color(255, 0, 0));
        RED1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RED1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/close.png"))); // NOI18N
        getContentPane().add(RED1, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 280, 60, 50));

        RED2.setFont(new java.awt.Font("PacFont", 1, 14)); // NOI18N
        RED2.setForeground(new java.awt.Color(255, 0, 0));
        RED2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RED2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/close.png"))); // NOI18N
        getContentPane().add(RED2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 370, -1, 50));

        RED3.setFont(new java.awt.Font("PacFont", 1, 14)); // NOI18N
        RED3.setForeground(new java.awt.Color(255, 0, 0));
        RED3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RED3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/close.png"))); // NOI18N
        getContentPane().add(RED3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 190, 50, 50));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 150, 90));

        username.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        username.setBorder(null);
        username.setOpaque(false);
        username.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                usernameMouseMoved(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 194, 320, 40));

        confirmpass.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        confirmpass.setBorder(null);
        confirmpass.setOpaque(false);
        confirmpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpassActionPerformed(evt);
            }
        });
        getContentPane().add(confirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 379, 320, 40));

        password.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        password.setBorder(null);
        password.setOpaque(false);
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 285, 320, 40));

        HoverBar.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        HoverBar.setForeground(new java.awt.Color(51, 51, 51));
        HoverBar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HoverBar.setBorder(null);
        HoverBar.setOpaque(false);
        HoverBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoverBarActionPerformed(evt);
            }
        });
        getContentPane().add(HoverBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, 410, 40));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 120, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\GABRIEL\\Documents\\NetBeansProjects\\FINALYEAR\\src\\images\\SIGNUP4.png")); // NOI18N
        jLabel4.setText("z");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 980, 630));

        setSize(new java.awt.Dimension(997, 669));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        
        
        new login().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
           ValidateSignup();
           new login().setVisible(true);
           this.dispose();
        //validating the form

    }//GEN-LAST:event_jLabel2MouseClicked

    private void confirmpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmpassActionPerformed

    private void HoverBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoverBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoverBarActionPerformed

    private void usernameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseMoved
        // TODO add your handling code here:
        HoverBar.setText("Enter your username here");
    }//GEN-LAST:event_usernameMouseMoved

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    private void ValidateSignup() {
        if (this.username.getText().equalsIgnoreCase("")) {
            RED3.setVisible(true);
        } else if (this.password.getText().equals("")) {
            RED1.setVisible(true);
        } else if (this.confirmpass.getText().equals("")) {
            RED2.setVisible(true);
        } else if (this.password.getText().equals(this.confirmpass.getText())) {
            String username = this.username.getText();
            String password = new String(this.password.getPassword());
            String confirmpass = new String(this.confirmpass.getPassword());

            user u = new user();
            u.setID(0);
            u.setUsername(username);
            u.setPassword(password);
            u.setConfirmpass(confirmpass);

            UserController uc = new UserController();
            int res = uc.createAccount(u);

            if (res > 0) {
                JOptionPane.showMessageDialog(null, "saved");
                new login().setVisible(true);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(null, "unable to save");

            }
        } else {
            JOptionPane.showMessageDialog(null, "your passwords doesnot match");

        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HoverBar;
    private javax.swing.JLabel RED1;
    private javax.swing.JLabel RED2;
    private javax.swing.JLabel RED3;
    private javax.swing.JPasswordField confirmpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
