/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import Controllers.upLoadingDatabase;
import Database.Database;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author GABRIEL
 */
public class Stepper1 extends javax.swing.JFrame {

    /**
     * Creates new form Stepper1
     */
    public Stepper1() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        patientName = new javax.swing.JTextField();
        patientID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Main = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(980, 630));
        jPanel1.setPreferredSize(new java.awt.Dimension(980, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 530, 140, 60));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 530, 150, 60));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 526, 140, 70));

        patientName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        patientName.setBorder(null);
        patientName.setOpaque(false);
        patientName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                patientNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                patientNameKeyReleased(evt);
            }
        });
        jPanel1.add(patientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 372, 320, 37));

        patientID.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        patientID.setBorder(null);
        patientID.setOpaque(false);
        patientID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                patientIDKeyPressed(evt);
            }
        });
        jPanel1.add(patientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 215, 33));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 360, 260));

        Main.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diagnosing2 Recovered.png"))); // NOI18N
        jPanel1.add(Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(998, 677));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new Stepper2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        new Register().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        new Lab().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void patientNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patientNameKeyReleased
        // TODO add your handling code here:


    }//GEN-LAST:event_patientNameKeyReleased

    private void patientNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patientNameKeyPressed
        // TODO add your handling code here:
      
            try {
                Database db = new Database();
                Connection Con;
                PreparedStatement pst;
                ResultSet ty;

                Con = db.getconnection();

                pst = Con.prepareStatement("SELECT * FROM `patientregistration` WHERE `patientName`=? ");
                pst.setString(1, patientName.getText());

                ty = pst.executeQuery();
                if (ty.next()) {
                    patientID.setText(ty.getString("patientID"));
                }

            } catch (Exception er) {
                JOptionPane.showMessageDialog(null, er.getMessage());
            }

        


    }//GEN-LAST:event_patientNameKeyPressed

    private void patientIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patientIDKeyPressed
        // TODO add your handling code here:
          try {
                Database db = new Database();
                Connection Con;
                PreparedStatement pst;
                ResultSet ty;

                Con = db.getconnection();

                pst = Con.prepareStatement("SELECT * FROM `patientregistration` WHERE `patientID`=? ");
                pst.setString(1, patientID.getText());

                ty = pst.executeQuery();
                if (ty.next()) {
                    patientName.setText(ty.getString("patientName"));
                }

            } catch (Exception er) {
                JOptionPane.showMessageDialog(null, er.getMessage());
            }
     

    }//GEN-LAST:event_patientIDKeyPressed
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stepper1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stepper1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stepper1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stepper1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stepper1().setVisible(true);
            }
        });
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("close.png")));
    }
    //creating the connection a between the textfield and mysql

    public void Idfind() {
        try {

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Only Integers");
        }

    }

    public void nameFinder() {

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Main;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField patientID;
    private javax.swing.JTextField patientName;
    // End of variables declaration//GEN-END:variables
}
